# Generated by Django 5.1.4 on 2024-12-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Emporium User', 'verbose_name_plural': 'Emporium Users'},
        ),
    ]
